/* Mastery (FCE) — Essay Vocab Lab, expansion pack II (+72 upgrades).
   Same contract as data-vocab.js: basic = the flat word; up = accepted band-boosting
   alternatives (first = headline); s = real essay frame with ____; why = examiner note. */
window.FCE = window.FCE || {};
FCE.VOCAB = FCE.VOCAB.concat([
{basic:"think about", up:["consider","take into account","weigh up"], s:"Before banning cars, councils should ____ the needs of older residents.", why:"consider + object = the essay verb for balanced arguments."},
{basic:"solve", up:["resolve","remedy","overcome"], s:"Better street lighting alone will not ____ the problem of night-time safety.", why:"resolve problems, overcome obstacles — precision verbs."},
{basic:"very good", up:["outstanding","exceptional","superb"], s:"The festival’s volunteer team did an ____ job this year.", why:"one strong adjective beats 'very + weak adjective' every time."},
{basic:"very bad", up:["dreadful","appalling","atrocious"], s:"The state of the changing rooms is frankly ____.", why:"graded condemnation — examiners hear the register shift."},
{basic:"nice (people)", up:["considerate","welcoming","kind-hearted"], s:"The host family could not have been more ____.", why:"'nice' says nothing; considerate/welcoming say HOW they were nice."},
{basic:"clever", up:["gifted","talented","sharp"], s:"Even the most ____ students need feedback to improve.", why:"gifted/talented = ability language for education essays."},
{basic:"weird", up:["peculiar","unusual","odd"], s:"There is something ____ about a beach town in winter.", why:"'weird' is spoken English; peculiar/odd carry the same idea formally."},
{basic:"old (things)", up:["outdated","obsolete","old-fashioned"], s:"Much of the school’s computer equipment is now hopelessly ____.", why:"outdated = no longer useful; old = just age. Examiners notice the difference."},
{basic:"new (ideas)", up:["innovative","groundbreaking","original"], s:"The company rewards employees who propose ____ solutions.", why:"innovative praises the NEWNESS of thinking, not the date."},
{basic:"kids", up:["young people","adolescents","teenagers"], s:"Social media places enormous pressure on ____ to look perfect.", why:"'kids' is chat language — never let it into a B2 essay."},
{basic:"everybody knows", up:["it is widely acknowledged","it is generally accepted","it is well known"], s:"____ that regular exercise improves concentration.", why:"impersonal openers sound researched instead of chatty."},
{basic:"a lot (adverb)", up:["considerably","significantly","substantially"], s:"Cycling lanes have improved road safety ____ since 2020.", why:"one precise adverb replaces a vague intensifier."},
{basic:"not enough", up:["insufficient","inadequate","lacking"], s:"The evidence against the new policy is simply ____.", why:"negative evaluation without writing 'not' — elegant economy."},
{basic:"right (justified)", up:["justified","well-founded","legitimate"], s:"Parents’ concerns about screen time are entirely ____.", why:"justified = right for a REASON — the essay sense of 'right'."},
{basic:"clear", up:["evident","apparent","obvious"], s:"It is ____ that tourism brings both income and pressure to the island.", why:"It is evident that… — the classic analysis frame."},
{basic:"hard (difficult)", up:["demanding","challenging","tough"], s:"Combining a job with full-time study is extremely ____.", why:"demanding/challenging describe difficulty without complaint."},
{basic:"easy", up:["straightforward","simple","effortless"], s:"Registering to vote online is quick and ____.", why:"straightforward = easy in the procedural sense essays need."},
{basic:"dangerous", up:["hazardous","risky","unsafe"], s:"Cycling without lights is genuinely ____ after dark.", why:"hazardous conditions, risky decisions — pick the precise danger."},
{basic:"dirty (environment)", up:["polluted","contaminated"], s:"The river is too ____ for swimming after heavy rain.", why:"polluted/contaminated = the environmental register."},
{basic:"clean (energy)", up:["renewable","sustainable","green"], s:"The island now gets half its power from ____ sources.", why:"renewable/sustainable — compulsory vocabulary for environment essays."},
{basic:"worrying", up:["alarming","disturbing","troubling"], s:"The rise in food prices is deeply ____ for young families.", why:"alarming statistics, disturbing trends — strong evaluative pairs."},
{basic:"money (public)", up:["funding","resources","investment"], s:"Local libraries close when ____ is cut.", why:"funding/resources = the vocabulary of policy essays."},
{basic:"job", up:["occupation","position","career"], s:"Choosing an ____ at eighteen is a daunting prospect.", why:"occupation/position = formal; career = the long view."},
{basic:"free time", up:["leisure time","spare time"], s:"Longer working hours leave employees with little ____ for sport.", why:"leisure time is the survey-and-essay term."},
{basic:"buy", up:["purchase","acquire"], s:"More households now ____ groceries online than in person.", why:"purchase = formal register; acquire = gain possession over time."},
{basic:"agree with", up:["support","be in favour of","back"], s:"Most residents ____ the plan for a car-free centre.", why:"support/be in favour of = stance verbs for opinion essays."},
{basic:"disagree with", up:["oppose","object to","reject"], s:"Many shop owners ____ the new parking charges.", why:"oppose needs no preposition — instant precision."},
{basic:"ask for", up:["request","call for","demand"], s:"Residents have ____ a meeting with the council about the noise.", why:"requested politely, demanded forcefully — choose your strength."},
{basic:"tell", up:["inform","notify"], s:"Passengers complain that nobody bothered to ____ them of the cancellation.", why:"inform somebody OF something — full B2 frame."},
{basic:"find out", up:["discover","establish","determine"], s:"Researchers hope to ____ why teenagers sleep so late.", why:"discover facts, establish causes — research verbs."},
{basic:"look at closely", up:["examine","analyse","investigate"], s:"This essay will ____ the arguments on both sides.", why:"the introduction verb examiners expect to see."},
{basic:"check", up:["verify","monitor"], s:"Apps now let parents ____ how long children spend online.", why:"verify facts, monitor processes — precise checking."},
{basic:"keep (preserve)", up:["preserve","retain","safeguard"], s:"We must ____ historic buildings even when land is valuable.", why:"preserve traditions/buildings — heritage-essay vocabulary."},
{basic:"make smaller", up:["reduce","decrease","cut down on"], s:"Car-free Sundays would ____ pollution in the city centre.", why:"reduce + noun is the workhorse; cut down ON for habits."},
{basic:"go up", up:["rise","increase","soar"], s:"Rents continue to ____ faster than salaries.", why:"rise (neutral) vs soar (dramatic) — trend language with attitude."},
{basic:"go down", up:["fall","decline","drop"], s:"Cinema attendance tends to ____ when streaming gets cheaper.", why:"decline adds the idea of long-term weakening."},
{basic:"get worse", up:["deteriorate","worsen","decline"], s:"Air quality tends to ____ during windless winter weeks.", why:"deteriorate = get worse, in a lab coat."},
{basic:"get better (after illness)", up:["recover","recuperate"], s:"It took her almost a month to ____ from the operation.", why:"recover FROM — health-topic essential."},
{basic:"build", up:["construct","develop","erect"], s:"The council plans to ____ affordable flats on the old factory site.", why:"construct buildings, develop areas — town-planning register."},
{basic:"destroy", up:["demolish","devastate","ruin"], s:"Floods can ____ a harvest in a single night.", why:"demolish buildings, devastate regions, ruin plans — match verb to victim."},
{basic:"fix", up:["repair","put right","rectify"], s:"The airline promised to ____ its booking system after the chaos.", why:"rectify mistakes = C1 polish; repair things."},
{basic:"choose", up:["select","opt for"], s:"Given the choice, most commuters would ____ the train over driving.", why:"opt FOR + noun — decision language."},
{basic:"let (allow)", up:["permit","enable","allow"], s:"Flexible hours ____ parents to collect children from school.", why:"enable somebody TO do = empowerment, not just permission."},
{basic:"force", up:["compel","oblige","pressure"], s:"Rising rents ____ many graduates to move back home.", why:"compel/oblige somebody TO do — formal causation."},
{basic:"avoid", up:["refrain from","steer clear of"], s:"Patients are advised to ____ caffeine before the test.", why:"refrain FROM + -ing = the formal warning frame."},
{basic:"join in", up:["participate in","take part in","engage in"], s:"Shy students rarely ____ class discussions without encouragement.", why:"participate IN — preposition included, mark secured."},
{basic:"stop doing (a habit)", up:["give up","quit","cut out"], s:"Her doctor told her to ____ sugary drinks completely.", why:"give up + noun/-ing — the habit-breaking phrasal examiners expect."},
{basic:"start (a hobby)", up:["take up","get into"], s:"More retirees are deciding to ____ painting or chess.", why:"TAKE UP a hobby — the partner of give up."},
{basic:"finish", up:["complete","conclude","finalise"], s:"Both bridges should be ____ before the tourist season.", why:"complete projects, conclude agreements."},
{basic:"answer (verb)", up:["respond to","reply to","address"], s:"The minister failed to ____ the journalists’ central question.", why:"respond TO — and 'address a question' = tackle it."},
{basic:"wait for", up:["await"], s:"Thousands of fans ____ the band’s arrival outside the hotel.", why:"await takes NO preposition — a neat C1-flavour swap."},
{basic:"cause (verb)", up:["lead to","result in","give rise to"], s:"Poor sleep can ____ serious problems with concentration.", why:"lead to / result in = the cause-effect chains essays are built from."},
{basic:"be caused by", up:["stem from","arise from"], s:"Most neighbour disputes ____ noise or parking.", why:"stem from flips the cause-effect arrow elegantly."},
{basic:"spend time", up:["devote time to","dedicate time to"], s:"Schools should ____ teaching basic cookery.", why:"devote/dedicate time TO + -ing — commitment vocabulary."},
{basic:"worried", up:["concerned","anxious","apprehensive"], s:"Many parents are ____ about the amount of homework set.", why:"concerned ABOUT = worried, professionally dressed."},
{basic:"surprising", up:["striking","remarkable","astonishing"], s:"It is ____ how quickly children adapt to new technology.", why:"striking/remarkable = surprise that invites analysis."},
{basic:"huge", up:["enormous","vast","immense"], s:"Hosting the festival requires an ____ amount of voluntary work.", why:"enormous/vast/immense — the formal giants."},
{basic:"tiny", up:["minimal","negligible","slight"], s:"The new tax will have only a ____ effect on most salaries.", why:"negligible = so small it can be ignored — perfect for counter-arguments."},
{basic:"fast", up:["rapid","swift"], s:"The ____ growth of online shopping has emptied many high streets.", why:"rapid growth/change — THE trend collocation."},
{basic:"slow", up:["gradual","sluggish"], s:"Progress on recycling targets has been disappointingly ____.", why:"gradual = neutral pace; sluggish = criticised pace."},
{basic:"often", up:["frequently","regularly"], s:"Trains on this line are ____ delayed in winter.", why:"frequently/regularly — adverbs that sound measured, not moaning."},
{basic:"sometimes", up:["occasionally","from time to time"], s:"Even experienced drivers ____ misjudge the roundabout.", why:"occasionally softens a claim — useful for balanced paragraphs."},
{basic:"always", up:["invariably","consistently"], s:"The bakery is ____ sold out by mid-morning.", why:"invariably = always, with a hint of evidence behind it."},
{basic:"hardly ever", up:["rarely","seldom"], s:"Politicians ____ admit that a policy has failed.", why:"rarely/seldom can even start a sentence with inversion: Rarely DO they admit…"},
{basic:"for example", up:["for instance","such as","to illustrate"], s:"Several cities, ____ Valencia and Porto, now offer free museum Sundays.", why:"'such as' slots examples INTO the sentence — smoother than restarting."},
{basic:"to sum up", up:["in conclusion","on balance","all things considered"], s:"____ , the benefits of hosting the games outweigh the costs.", why:"on balance signals you have actually WEIGHED the arguments."},
{basic:"instead of", up:["rather than","as an alternative to"], s:"____ banning phones, schools could teach focused use.", why:"Rather than + -ing — contrast structures earn organisation marks."},
{basic:"at the same time", up:["simultaneously","meanwhile"], s:"The app translates and, ____ , corrects your grammar.", why:"simultaneously compresses 'at the same time' into one precise adverb."},
{basic:"because (conjunction)", up:["since","as","given that"], s:"____ the hall was double-booked, the concert moved outdoors.", why:"since/as at sentence start = cause without repeating 'because'."},
{basic:"good for the environment", up:["environmentally friendly","eco-friendly","sustainable"], s:"Bamboo cutlery is a cheap, ____ alternative to plastic.", why:"the hyphenated eco-adjectives — and a spelling test in disguise."},
{basic:"thing (factor)", up:["factor","aspect","element"], s:"Cost is the decisive ____ for most families choosing a holiday.", why:"'thing' is the emptiest word in English — factor/aspect always beats it."},
{basic:"result", up:["outcome","consequence"], s:"The ban had one unexpected ____ : cycling doubled in a year.", why:"outcome (neutral) vs consequence (often negative) — choose deliberately."},
]);
