/* Mastery (FCE) — question bank VI (k111–k130, c138–c157, w109–w128, m111–m130). */
window.FCE = window.FCE || {};
FCE.BANK = FCE.BANK || {};
(function(){
var K = [
{id:"k111", s1:"Driving without a seatbelt is against the law.", key:"ALLOWED", s2:"You are ____ without a seatbelt.", ans:["not allowed to drive"], halves:[["not allowed"],["to drive"]], tags:["pass","modal"], diff:2, exp:"against the law ↔ NOT ALLOWED TO + infinitive.", trap:"Keep TO: not allowed to drive."},
{id:"k112", s1:"The film didn’t live up to my expectations.", key:"GOOD", s2:"The film was not ____ I had expected.", ans:["as good as","so good as"], halves:[["as good","so good"],["as"]], tags:["comp"], diff:3, exp:"not AS/SO good AS.", trap:"Base adjective inside as…as — never 'better'."},
{id:"k113", s1:"“I’m sorry I’m late,” said Tom.", key:"FOR", s2:"Tom apologised ____ late.", ans:["for being","for arriving"], halves:[["for"],["being","arriving"]], tags:["rep","ger"], diff:2, exp:"apologise FOR + -ing.", trap:"'for to be late' / 'for be late' both fail."},
{id:"k114", s1:"This puzzle is too difficult for the children to solve.", key:"SIMPLE", s2:"This puzzle is not ____ for the children to solve.", ans:["simple enough"], halves:[["simple"],["enough"]], tags:["comp"], diff:2, exp:"too difficult ↔ not + opposite + ENOUGH.", trap:"enough AFTER the adjective."},
{id:"k115", s1:"People believe the painting was stolen to order.", key:"BELIEVED", s2:"The painting is ____ stolen to order.", ans:["believed to have been"], halves:[["believed to"],["have been"]], tags:["pass","rep"], diff:5, exp:"Impersonal passive + past: believed TO HAVE BEEN stolen.", trap:"The past reference needs HAVE BEEN, not just 'to be'."},
{id:"k116", s1:"We arrived too late to see the opening ceremony.", key:"TIME", s2:"We did not arrive in ____ the opening ceremony.", ans:["time to see","time for"], halves:[["time"],["to see","for"]], tags:["fix","prep"], diff:3, exp:"IN TIME to do / for something.", trap:"in time (early enough) ≠ on time (punctually)."},
{id:"k117", s1:"My sister is a much better cook than me.", key:"WELL", s2:"I do not cook ____ my sister.", ans:["as well as","so well as","nearly as well as"], halves:[["as well","so well","nearly as well"],["as"]], tags:["comp"], diff:3, exp:"adverb comparison: not as WELL as.", trap:"WELL (adverb), not GOOD, after a verb."},
{id:"k118", s1:"It’s possible that the keys are still in the car.", key:"MIGHT", s2:"The keys ____ in the car.", ans:["might still be","might be still"], halves:[["might"],["still be","be still"]], tags:["modal"], diff:2, exp:"Present possibility: MIGHT + be.", trap:"No TO after might."},
{id:"k119", s1:"The teacher made the class rewrite the essay.", key:"WAS", s2:"The class ____ rewrite the essay.", ans:["was made to"], halves:[["was made"],["to"]], tags:["pass"], diff:4, exp:"make sb do → passive BE MADE TO do.", trap:"The returning TO — Cambridge’s favourite half mark."},
{id:"k120", s1:"I haven’t spoken French since I left school.", key:"LAST", s2:"The ____ French was when I left school.", ans:["last time i spoke"], halves:[["last time"],["i spoke"]], tags:["fix","aux"], diff:3, exp:"present perfect negative + since ↔ the LAST TIME + past simple.", trap:"Past simple after 'the last time'."},
{id:"k121", s1:"He couldn’t find his passport anywhere.", key:"NOWHERE", s2:"His passport was ____ found.", ans:["nowhere to be"], halves:[["nowhere"],["to be"]], tags:["fix","pass"], diff:4, exp:"be NOWHERE TO BE found.", trap:"All four words fixed."},
{id:"k122", s1:"They will announce the results on Friday.", key:"BE", s2:"The results will ____ on Friday.", ans:["be announced"], halves:[["be"],["announced"]], tags:["pass"], diff:1, exp:"Future passive: will BE + participle.", trap:"Simple but rushed students write 'be announce'."},
{id:"k123", s1:"Maybe they didn’t receive our invitation.", key:"HAVE", s2:"They may not ____ our invitation.", ans:["have received","have got"], halves:[["have"],["received","got"]], tags:["modal"], diff:3, exp:"Past possibility negative: may not HAVE + participle.", trap:"'may not received' loses the HAVE."},
{id:"k124", s1:"I find it strange that she didn’t phone.", key:"ODD", s2:"It strikes me ____ she didn’t phone.", ans:["as odd that"], halves:[["as odd"],["that"]], tags:["fix"], diff:5, exp:"strike somebody AS + adjective.", trap:"strike as — elegant C1-flavour pattern."},
{id:"k125", s1:"Although he is rich, he lives very simply.", key:"DESPITE", s2:"He lives very simply ____ rich.", ans:["despite being"], halves:[["despite"],["being"]], tags:["link","ger"], diff:2, exp:"DESPITE + being + adjective.", trap:"despite OF — automatic zero."},
{id:"k126", s1:"“Did you lock the door, Sam?” asked Rosa.", key:"IF", s2:"Rosa asked Sam ____ the door.", ans:["if he had locked"], halves:[["if he"],["had locked"]], tags:["rep"], diff:3, exp:"Reported yes/no question: IF + past perfect.", trap:"Backshift did → had locked."},
{id:"k127", s1:"Eating in the library is forbidden.", key:"MUST", s2:"Food ____ in the library.", ans:["must not be eaten","mustn't be eaten","must not be consumed"], halves:[["must not","mustn't"],["be eaten","be consumed"]], tags:["pass","modal"], diff:3, exp:"Prohibition passive: MUST NOT BE + participle.", trap:"BE is the half students drop."},
{id:"k128", s1:"It was such an exciting match that nobody left early.", key:"SO", s2:"The match was ____ nobody left early.", ans:["so exciting that"], halves:[["so exciting"],["that"]], tags:["comp","det"], diff:2, exp:"such a + noun ↔ SO + adjective + that.", trap:"Mirror transformation — drop the noun, drop the article."},
{id:"k129", s1:"I’d prefer to go by train rather than fly.", key:"SOONER", s2:"I would ____ by train than fly.", ans:["sooner go","sooner travel"], halves:[["sooner"],["go","travel"]], tags:["wish","comp"], diff:4, exp:"would SOONER do = would rather do.", trap:"Bare infinitive after would sooner."},
{id:"k130", s1:"Whose idea was this brilliant plan?", key:"CAME", s2:"Who ____ this brilliant plan?", ans:["came up with"], halves:[["came up"],["with"]], tags:["pv"], diff:2, exp:"COME UP WITH = think of/invent — here in the past: came up with.", trap:"All three words needed; the particle pair UP WITH carries a full mark."},
];
var C = [
{id:"c138", s:"The success of the festival depends largely ____ the weather holding.", ans:["on","upon"], gt:"prep", tags:["prep"], diff:2, exp:"depend ON.", trap:"largely is a distractor between verb and preposition."},
{id:"c139", s:"It was kind ____ you to wait for me.", ans:["of"], gt:"prep", tags:["prep"], diff:2, exp:"kind/nice/good OF somebody to do.", trap:"kind FOR you — the judging-adjective pattern takes OF."},
{id:"c140", s:"____ average, it rains here one day in three.", ans:["on"], gt:"prep", tags:["depprep"], diff:2, exp:"ON average.", trap:"IN average is the standard miss."},
{id:"c141", s:"You ____ to see his face when he opened the box!", ans:["ought","had"], gt:"modal", tags:["modal"], diff:4, exp:"You OUGHT to have seen… (here: ought to see) — exclamation idiom.", trap:"OUGHT is the only modal with TO."},
{id:"c142", s:"The new bridge, ____ construction took five years, finally opened.", ans:["whose"], gt:"rel", tags:["rel"], diff:4, exp:"WHOSE works for things too: the bridge whose construction…", trap:"'which construction' is impossible."},
{id:"c143", s:"We could see the coast far ____ in the distance.", ans:["off","away","below"], gt:"adv", tags:["fix"], diff:2, exp:"far OFF / far AWAY = distant.", trap:"Multiple answers accepted — pick the one you're sure of."},
{id:"c144", s:"He is, ____ doubt, the finest goalkeeper of his generation.", ans:["without","beyond"], gt:"prep", tags:["fix"], diff:3, exp:"WITHOUT/BEYOND doubt = certainly.", trap:"'with no doubt' needs three words; the slot wants one."},
{id:"c145", s:"____ being injured, the captain insisted on playing.", ans:["despite"], gt:"link", tags:["link","ger"], diff:3, exp:"DESPITE + -ing.", trap:"Although + -ing is impossible."},
{id:"c146", s:"There’s a fine ____ between confidence and arrogance.", ans:["line"], gt:"vform", tags:["fix","col"], diff:4, exp:"a fine LINE between X and Y.", trap:"'fine limit/border' — the idiom owns LINE."},
{id:"c147", s:"I’ll meet you at the café ____ to the station entrance.", ans:["next","close"], gt:"adv", tags:["prep","fix"], diff:2, exp:"NEXT TO / CLOSE TO = beside.", trap:"NEAR takes no TO — that's why it can't fill this gap."},
{id:"c148", s:"She speaks four languages, two of ____ fluently.", ans:["them"], gt:"pron", tags:["pron","rel"], diff:4, exp:"two of THEM (no verb follows → pronoun, not which).", trap:"'two of which' needs a verb after it."},
{id:"c149", s:"____ a rule, I avoid sugary drinks during exam week.", ans:["as"], gt:"fixphrase", tags:["fix"], diff:3, exp:"AS a rule = generally.", trap:"'For a rule' / 'In a rule' miss the idiom."},
{id:"c150", s:"The lecture was so boring that I could hardly stay ____ .", ans:["awake"], gt:"vform", tags:["col"], diff:2, exp:"stay AWAKE.", trap:"'stay woke up' — the adjective is awake."},
{id:"c151", s:"Success in Part 4 comes ____ to knowing the patterns.", ans:["down"], gt:"adv", tags:["pv"], diff:4, exp:"COME DOWN TO = be essentially a matter of.", trap:"comes UP to / comes OUT to — only DOWN works."},
{id:"c152", s:"Neither the manager ____ the staff knew about the inspection.", ans:["nor"], gt:"link", tags:["link"], diff:2, exp:"neither … NOR.", trap:"'neither…or' is the classic loss."},
{id:"c153", s:"We were made to wait outside, ____ of the freezing wind.", ans:["regardless"], gt:"fixphrase", tags:["fix","link"], diff:4, exp:"REGARDLESS of = without considering.", trap:"'despite of' bait again — the word here is regardless."},
{id:"c154", s:"How did you get ____ in the end — did the bank lend you the money?", ans:["on","by"], gt:"adv", tags:["pv"], diff:3, exp:"get ON = progress; get BY = manage financially.", trap:"Both accepted; 'get by' is the money idiom."},
{id:"c155", s:"It’s no good ____ over spilt milk.", ans:["crying"], gt:"vform", tags:["fix","ger"], diff:3, exp:"it's no good + -ING; idiom: cry over spilt milk.", trap:"-ING after 'no good', and the idiom verb is cry."},
{id:"c156", s:"The escape was planned right ____ the guards’ noses.", ans:["under"], gt:"prep", tags:["fix"], diff:3, exp:"UNDER somebody's nose = in plain sight.", trap:"in front of their noses ✗ — idiom says under."},
{id:"c157", s:"____ I known about the strike, I would have driven.", ans:["had"], gt:"aux", tags:["cond","inv"], diff:4, exp:"HAD I known = If I had known.", trap:"The inversion replaces IF entirely."},
];
var W = [
{id:"w109", s:"The ____ of the volunteers made the event possible.", stem:"GENEROUS", ans:["generosity"], tags:["wfnoun"], diff:2, exp:"generous → generosity.", trap:"-OSITY: generosity, curiosity."},
{id:"w110", s:"Her ____ to give up impressed every coach.", stem:"REFUSE", ans:["refusal"], tags:["wfnoun"], diff:2, exp:"refuse → refusal.", trap:"-AL noun like arrival, approval."},
{id:"w111", s:"The defendant proved his ____ with a single receipt.", stem:"INNOCENT", ans:["innocence"], tags:["wfnoun"], diff:2, exp:"innocent → innocence.", trap:"-ENCE after -ent."},
{id:"w112", s:"City life offers endless ____ for networking.", stem:"OPPORTUNE", ans:["opportunities"], tags:["wfnoun","spell"], diff:3, exp:"opportune → opportunitIES (plural after 'endless').", trap:"Plural + double P."},
{id:"w113", s:"He answered with surprising ____ for a beginner.", stem:"MATURE", ans:["maturity"], tags:["wfnoun"], diff:2, exp:"mature → maturity.", trap:"Not 'matureness'."},
{id:"w114", s:"The instructions were so ____ that everyone got lost.", stem:"CONFUSE", ans:["confusing"], tags:["wfadj"], diff:2, exp:"-ING = what causes the feeling.", trap:"confused people, confusing instructions."},
{id:"w115", s:"Despite the rain, the fans remained ____ throughout.", stem:"ENTHUSIASM", ans:["enthusiastic"], tags:["wfadj","spell"], diff:3, exp:"enthusiasm → enthusiastic.", trap:"-IASTIC: enthus-iastic."},
{id:"w116", s:"Sadly, such kindness is highly ____ nowadays.", stem:"USUAL", ans:["unusual"], tags:["wfadj","wfneg"], diff:3, exp:"'Sadly' + 'such kindness' → UNusual.", trap:"Polarity hides in 'sadly'."},
{id:"w117", s:"The team played ____ in the second half.", stem:"BRILLIANT", ans:["brilliantly"], tags:["wfadv"], diff:1, exp:"brilliant → brilliantly.", trap:"Double L survives: brilliantly."},
{id:"w118", s:"____ speaking, the project was a failure.", stem:"STRICT", ans:["strictly"], tags:["wfadv"], diff:2, exp:"STRICTLY speaking — fixed discourse adverb.", trap:"Sentence-initial adverb pattern."},
{id:"w119", s:"There has been a ____ improvement in air quality.", stem:"NOTICE", ans:["noticeable"], tags:["wfadj","spell"], diff:3, exp:"notice → noticeable.", trap:"Keep the E: notice-able."},
{id:"w120", s:"The hotel pool is for ____ use only.", stem:"RESIDE", ans:["residents'","residents"], tags:["wfnoun"], diff:4, exp:"reside → residents (possessive idea).", trap:"Person noun, plural."},
{id:"w121", s:"Volunteers worked ____ to clear the beach.", stem:"TIRE", ans:["tirelessly"], tags:["wfadv","wfneg"], diff:4, exp:"tire → tireless → tirelessly: two suffixes.", trap:"Double transformation: -less + -ly."},
{id:"w122", s:"The ____ between the two reports is striking.", stem:"SIMILAR", ans:["similarity"], tags:["wfnoun"], diff:2, exp:"similar → similarity.", trap:"-ITY noun."},
{id:"w123", s:"Smoking is strictly ____ on all flights.", stem:"FORBID", ans:["forbidden"], tags:["wfadj","spell"], diff:2, exp:"forbid → forbidden.", trap:"Double D in the participle."},
{id:"w124", s:"Her ____ smile put the candidates at ease.", stem:"FRIEND", ans:["friendly"], tags:["wfadj"], diff:1, exp:"friend → friendly.", trap:"-LY here makes an ADJECTIVE, not an adverb."},
{id:"w125", s:"The medicine must be kept out of children’s ____ .", stem:"REACH", ans:["reach"], tags:["wfnoun","fix"], diff:4, exp:"out of REACH — the stem already fits.", trap:"No-change trap inside a fixed phrase."},
{id:"w126", s:"The committee questioned the ____ of the figures.", stem:"RELY", ans:["reliability"], tags:["wfnoun","spell"], diff:3, exp:"rely → reliable → reliability.", trap:"y→i, then -ability."},
{id:"w127", s:"____ , the two scientists reached the same conclusion.", stem:"DEPEND", ans:["independently"], tags:["wfadv","wfneg"], diff:4, exp:"depend → independent → independently.", trap:"Prefix + double suffix — triple step."},
{id:"w128", s:"The story’s ending was completely ____ .", stem:"EXPECT", ans:["unexpected"], tags:["wfadj","wfneg"], diff:2, exp:"'completely' + twist → UNexpected.", trap:"unexpected, not 'inexpected'."},
];
var M = [
{id:"m111", s:"The smell of fresh bread ____ me of my grandmother’s kitchen.", opts:["reminds","remembers","recalls","reflects"], cor:0, tags:["col"], diff:1, exp:"REMIND somebody OF.", trap:"remember can't take an object + of."},
{id:"m112", s:"Could you keep me ____ of any changes to the schedule?", opts:["informed","known","acquainted","told"], cor:0, tags:["col","pass"], diff:3, exp:"keep somebody INFORMED of.", trap:"'keep me aware' is weak; the collocation is informed."},
{id:"m113", s:"The committee ____ doubts about the project’s funding.", opts:["raised","rose","lifted","aroused"], cor:0, tags:["col"], diff:3, exp:"RAISE doubts/questions/concerns.", trap:"rise is intransitive; arouse suspicion but raise doubts."},
{id:"m114", s:"I’m afraid your account doesn’t ____ with the other witness’s.", opts:["agree","accept","admit","approve"], cor:0, tags:["col","prep"], diff:3, exp:"AGREE WITH = be consistent with.", trap:"accounts agree; people accept things."},
{id:"m115", s:"After the scandal, the minister was forced to ____ down.", opts:["stand","bow","sit","fall"], cor:0, tags:["pv"], diff:3, exp:"STAND DOWN = resign from a position.", trap:"bow OUT also means leave — but bow DOWN means worship."},
{id:"m116", s:"It took her years to ____ a reputation as a reliable builder.", opts:["build","make","grow","raise"], cor:0, tags:["col"], diff:2, exp:"BUILD a reputation.", trap:"make a name, but build a reputation."},
{id:"m117", s:"The two countries finally ____ peace after a decade of war.", opts:["made","did","built","created"], cor:0, tags:["col"], diff:1, exp:"MAKE peace.", trap:"make war, make peace — both with make."},
{id:"m118", s:"I can’t ____ on an empty stomach — let’s eat first.", opts:["concentrate","attend","reflect","think"], cor:0, tags:["col","prep"], diff:2, exp:"CONCENTRATE (on).", trap:"attend TO exists but means deal with."},
{id:"m119", s:"The ferry service was ____ because of high winds.", opts:["suspended","interrupted","paused","expelled"], cor:0, tags:["col"], diff:3, exp:"services are SUSPENDED.", trap:"formal service verb: suspend."},
{id:"m120", s:"Her argument simply doesn’t ____ water.", opts:["hold","keep","carry","stand"], cor:0, tags:["fix"], diff:4, exp:"HOLD water = be logically sound.", trap:"Pure idiom — hold."},
{id:"m121", s:"We need to ____ a balance between price and quality.", opts:["strike","hit","beat","knock"], cor:0, tags:["col"], diff:3, exp:"STRIKE a balance.", trap:"strike a balance / strike a deal."},
{id:"m122", s:"They’ve put ____ an offer on a house near the coast.", opts:["in","out","up","over"], cor:0, tags:["pv","col"], diff:3, exp:"PUT IN an offer = formally make one.", trap:"put in (submit) vs put up (display/raise) vs put out (extinguish)."},
{id:"m123", s:"The plan sounds good ____ paper, but it will never work.", opts:["on","in","at","by"], cor:0, tags:["depprep","fix"], diff:2, exp:"ON paper = in theory.", trap:"IN paper is the L1 calque."},
{id:"m124", s:"He paid the fine rather ____ go to court.", opts:["than","then","that","to"], cor:0, tags:["comp","link"], diff:2, exp:"rather THAN + bare infinitive.", trap:"than/then — one letter, one mark."},
{id:"m125", s:"The book gives a fascinating ____ into Victorian life.", opts:["insight","outlook","view","sight"], cor:0, tags:["col"], diff:3, exp:"INSIGHT INTO.", trap:"view OF, outlook ON, insight INTO."},
{id:"m126", s:"My phone is ____ its last legs — the battery dies by noon.", opts:["on","at","in","by"], cor:0, tags:["fix"], diff:3, exp:"ON its last legs = nearly worn out.", trap:"Fixed: on."},
{id:"m127", s:"____ the circumstances, the team performed admirably.", opts:["Given","Granted","Provided","Supposing"], cor:0, tags:["link"], diff:4, exp:"GIVEN + noun = considering.", trap:"provided/supposing need clauses."},
{id:"m128", s:"The trainer told us to warm up so as not to ____ a muscle.", opts:["pull","drag","stretch","snap"], cor:0, tags:["col"], diff:2, exp:"PULL a muscle.", trap:"stretch is what you should do; pull is the injury."},
{id:"m129", s:"Sales ____ a record high in December.", opts:["hit","struck","banged","met"], cor:0, tags:["col"], diff:2, exp:"HIT a record high.", trap:"hit a high, break a record — don't blend."},
{id:"m130", s:"I only know her ____ sight, not to talk to.", opts:["by","of","from","at"], cor:0, tags:["depprep","fix"], diff:3, exp:"know somebody BY sight.", trap:"BY sight / BY name / BY heart — the by-family."},
];
FCE.BANK.kwt = FCE.BANK.kwt.concat(K);
FCE.BANK.cloze = FCE.BANK.cloze.concat(C);
FCE.BANK.wf = FCE.BANK.wf.concat(W);
FCE.BANK.mcc = FCE.BANK.mcc.concat(M);
})();
