/* Mastery (FCE) — Essay Vocab Lab data.
   Each entry upgrades a "flat" word into band-boosting alternatives, anchored in a real
   essay sentence (the strongest retrieval cue). basic = the weak word; up = accepted
   upgrades (first = headline); s = essay frame with ____; why = examiner note. */
window.FCE = window.FCE || {};
FCE.VOCAB = [
{basic:"very important", up:["crucial","vital","essential"], s:"Reducing plastic waste is ____ if coastal cities are to survive.", why:"B2 writing scores jump when 'very + adjective' becomes one precise word."},
{basic:"good", up:["beneficial"], s:"Regular exercise is highly ____ to concentration and mood.", why:"beneficial TO — collocates like a dream in essays."},
{basic:"bad", up:["detrimental","harmful"], s:"Excessive screen time can be ____ to teenagers’ sleep.", why:"detrimental TO = formal, precise damage."},
{basic:"big", up:["considerable","substantial","significant"], s:"Hosting the games requires a ____ amount of public money.", why:"the three official 'big numbers' words of academic English."},
{basic:"think", up:["argue","maintain","contend"], s:"Many experts ____ that homework should be limited.", why:"reporting verbs make your essay sound researched, not personal."},
{basic:"show", up:["demonstrate","illustrate","reveal"], s:"Recent studies clearly ____ the link between sleep and memory.", why:"demonstrate/illustrate = evidence language examiners reward."},
{basic:"say", up:["claim","state","assert"], s:"Supporters of the ban ____ that it will reduce accidents.", why:"claim adds healthy distance from an opinion."},
{basic:"get", up:["obtain","acquire","gain"], s:"Students ____ valuable experience through part-time work.", why:"gain experience / acquire skills / obtain qualifications."},
{basic:"give", up:["provide","offer","supply"], s:"Volunteering can ____ young people with a sense of purpose.", why:"provide somebody WITH something — full B2 frame."},
{basic:"help", up:["contribute to","facilitate"], s:"Green spaces ____ residents’ wellbeing in measurable ways.", why:"contribute to = cause-language without overclaiming."},
{basic:"use", up:["employ","utilise","utilize"], s:"Schools should ____ technology more imaginatively.", why:"employ a method/strategy — instant register lift."},
{basic:"start", up:["launch","initiate","establish"], s:"The council plans to ____ a free bike-sharing scheme.", why:"launch schemes, initiate programmes, establish systems."},
{basic:"stop (something)", up:["prevent","prohibit","ban"], s:"Stricter rules would ____ companies from misleading consumers.", why:"prevent X FROM -ing — examiner catnip."},
{basic:"make worse", up:["aggravate","worsen","exacerbate"], s:"Building more roads may actually ____ congestion.", why:"exacerbate = C1-flavour; aggravate is the safe B2+ pick."},
{basic:"make better", up:["enhance","improve","boost"], s:"Cultural exchanges ____ mutual understanding between countries.", why:"enhance understanding / boost confidence."},
{basic:"a lot of", up:["a great deal of","numerous"], s:"Tourism brings ____ money into the local economy.", why:"a great deal of + uncountable; numerous + plural."},
{basic:"more and more", up:["increasingly"], s:"Remote work is becoming ____ common across Europe.", why:"one adverb replaces a clunky phrase — instant precision."},
{basic:"but", up:["however","nevertheless","nonetheless"], s:"The plan is expensive; ____ , its long-term benefits are clear.", why:"sentence-linking contrast = structure marks in Writing."},
{basic:"so", up:["consequently","therefore","as a result"], s:"Fuel prices rose sharply; ____ , bus use increased.", why:"consequence linkers organise paragraphs."},
{basic:"also", up:["furthermore","moreover","in addition"], s:"____ , cycling reduces noise pollution in city centres.", why:"paragraph-opening adders signal essay architecture."},
{basic:"because of", up:["owing to","due to"], s:"The match was postponed ____ torrential rain.", why:"owing to + noun = formal cause."},
{basic:"about (a topic)", up:["regarding","concerning"], s:"Opinions differ widely ____ the voting age.", why:"regarding/concerning = topic language for introductions."},
{basic:"now", up:["currently","at present","nowadays"], s:"____ , over half of humanity lives in cities.", why:"essay-opening time frames."},
{basic:"in the end", up:["ultimately","eventually"], s:"____ , the decision rests with individual families.", why:"ultimately signals your conclusion is coming."},
{basic:"clearly", up:["evidently","undoubtedly","undeniably"], s:"____ , social media has transformed how teenagers communicate.", why:"stance adverbs — confident, examiner-friendly."},
{basic:"people think", up:["it is widely believed"], s:"____ that exams cause unnecessary stress.", why:"impersonal passive = the single most useful essay frame at B2."},
{basic:"I think", up:["from my perspective","in my view"], s:"____ , the advantages clearly outweigh the drawbacks.", why:"vary 'In my opinion' — examiners read it 200 times a day."},
{basic:"problem", up:["issue","challenge","drawback"], s:"The main ____ of online learning is the lack of real contact.", why:"drawback pairs with advantage; issue sounds analytical."},
{basic:"advantage", up:["benefit","merit"], s:"A key ____ of public transport is its low cost per passenger.", why:"rotate advantage/benefit/merit to avoid repetition."},
{basic:"disadvantage", up:["drawback","downside"], s:"One serious ____ of tourism is the pressure on housing.", why:"drawback/downside — natural, precise."},
{basic:"important issue", up:["pressing issue","burning issue"], s:"Climate change remains the most ____ of our time.", why:"pressing/burning = urgency collocations."},
{basic:"effect", up:["impact","consequence"], s:"Advertising has a powerful ____ on children’s eating habits.", why:"impact ON — strong noun, strong preposition."},
{basic:"reason", up:["motive","grounds"], s:"There are strong ____ for investing in rail rather than roads.", why:"grounds FOR -ing = high-band noun."},
{basic:"way", up:["approach","method","means"], s:"Car-sharing is an effective ____ of cutting emissions.", why:"means OF -ing; approach TO."},
{basic:"young people", up:["adolescents","the younger generation"], s:"____ are often unfairly portrayed in the media.", why:"vary 'teenagers' across an essay."},
{basic:"old people", up:["the elderly","senior citizens"], s:"____ often possess experience that workplaces undervalue.", why:"respectful, formal register."},
{basic:"everyone", up:["the general public","society as a whole"], s:"Museums should be free to ____ .", why:"audience nouns beat vague 'everyone'."},
{basic:"poor people", up:["disadvantaged groups","low-income families"], s:"Rising rents hit ____ hardest.", why:"precise, neutral, essay-appropriate."},
{basic:"rich", up:["affluent","wealthy"], s:"The festival mainly attracts visitors from ____ backgrounds.", why:"affluent backgrounds/areas — classic collocation."},
{basic:"cheap", up:["affordable","economical"], s:"Cities need more ____ housing for key workers.", why:"affordable = cheap without the negative tone."},
{basic:"expensive", up:["costly"], s:"Repairing the damage later will prove far more ____ than preventing it.", why:"costly works for money AND consequences."},
{basic:"famous", up:["renowned","celebrated"], s:"The region is ____ for its medieval festivals.", why:"renowned FOR — prestige collocation."},
{basic:"interesting", up:["fascinating","compelling"], s:"The documentary offers a ____ insight into city life.", why:"kill 'interesting' in essays; it says nothing."},
{basic:"boring", up:["monotonous","tedious"], s:"Without variety, even a dream job becomes ____ .", why:"monotonous = boring with a reason."},
{basic:"happy", up:["content","satisfied"], s:"Workers with flexible hours report feeling more ____ .", why:"content/satisfied = measured, adult emotion words."},
{basic:"sad", up:["regrettable","disheartening"], s:"It is ____ that so few residents attend local meetings.", why:"'It is regrettable that' — formal evaluation frame."},
{basic:"angry", up:["frustrated","outraged"], s:"Commuters are increasingly ____ by constant delays.", why:"graded anger: frustrated < outraged."},
{basic:"scared", up:["apprehensive","alarmed"], s:"Many parents feel ____ about their children’s online safety.", why:"apprehensive ABOUT — precise worry."},
{basic:"tired", up:["exhausted","drained"], s:"Shift workers often arrive home utterly ____ .", why:"intensify properly: utterly exhausted."},
{basic:"sure", up:["convinced","certain"], s:"I am ____ that small changes can have national effects.", why:"convinced THAT — conviction frame for conclusions."},
{basic:"wrong", up:["mistaken","flawed"], s:"The assumption that growth is endless is deeply ____ .", why:"flawed arguments, mistaken beliefs."},
{basic:"enough", up:["sufficient","adequate"], s:"Few schools devote ____ time to financial education.", why:"sufficient/adequate = measured judgement."},
{basic:"too much", up:["excessive"], s:"____ packaging remains the supermarkets’ dirty secret.", why:"excessive + noun beats 'too much' in formal writing."},
{basic:"need (verb)", up:["require","call for"], s:"Tackling obesity will ____ action on many fronts.", why:"call for = demand — editorial register."},
{basic:"want", up:["be eager to","be keen to"], s:"Most graduates ____ gain international experience.", why:"eager/keen TO — motivated, formal."},
{basic:"deal with", up:["address","tackle"], s:"Governments must ____ the housing shortage urgently.", why:"address/tackle problems — the essay verbs."},
{basic:"happen", up:["occur","take place","arise"], s:"Misunderstandings often ____ when instructions are vague.", why:"arise for problems, occur for events."},
{basic:"change (noun)", up:["shift","transformation"], s:"The last decade has seen a dramatic ____ in shopping habits.", why:"a shift IN — analytical change-language."},
];
