/* FCE Mastery — question bank II: Word Formation (Part 3), Multiple-Choice Cloze (Part 1),
   and full exam-style passages for mock tests. */
window.FCE = window.FCE || {};
FCE.BANK = FCE.BANK || {};

/* ---------- Word Formation (stem given in capitals, one word answer) ---------- */
FCE.BANK.wf = [
{id:"w01", s:"Her ____ to adapt to new situations impressed the interviewers.", stem:"ABLE", ans:["ability"], tags:["wfnoun"], diff:1, exp:"able → ability (noun, -ity).", trap:"Check it isn’t negative: the sentence is positive, so not 'inability'."},
{id:"w02", s:"After three ____ attempts, she finally passed her driving test.", stem:"SUCCEED", ans:["unsuccessful"], tags:["wfadj","wfneg"], diff:3, exp:"succeed → successful → UNsuccessful. 'After … finally passed' forces the negative.", trap:"The polarity trap: write 'successful' and you lose the mark."},
{id:"w03", s:"Moving abroad was the best ____ I have ever made.", stem:"DECIDE", ans:["decision"], tags:["wfnoun","spell"], diff:1, exp:"decide → decision (-sion).", trap:"Spelling: deciSion, not decition."},
{id:"w04", s:"The story is told with extraordinary ____ and humour.", stem:"IMAGINE", ans:["imagination"], tags:["wfnoun"], diff:1, exp:"imagine → imagination.", trap:"Not 'imaginations' — abstract noun stays singular here."},
{id:"w05", s:"The market for streaming services has become fiercely ____ .", stem:"COMPETE", ans:["competitive"], tags:["wfadj"], diff:2, exp:"compete → competitive (-itive).", trap:"'competing' is grammatical but weaker — Cambridge wants the adjective."},
{id:"w06", s:"Youth ____ has fallen to its lowest level in a decade.", stem:"EMPLOY", ans:["unemployment"], tags:["wfnoun","wfneg"], diff:3, exp:"'has fallen' + good news = UNemployment falling.", trap:"'employment has fallen' would be bad news — read the logic, not just the gap."},
{id:"w07", s:"There is no ____ proof that the remedy actually works.", stem:"SCIENCE", ans:["scientific"], tags:["wfadj"], diff:1, exp:"science → scientific (-ific).", trap:"Spelling: scien-TI-fic."},
{id:"w08", s:"Surprisingly, the flavour of the dish was completely ____ .", stem:"NATURE", ans:["natural","unnatural"], tags:["wfadj"], diff:2, exp:"nature → natural; 'Surprisingly' allows unnatural too — both accepted here.", trap:"In the real exam, read the surrounding sentences to fix polarity."},
{id:"w09", s:"Climbing without ropes puts climbers in serious ____ .", stem:"DANGEROUS", ans:["danger"], tags:["wfnoun"], diff:2, exp:"Adjective given, noun needed: danger.", trap:"Reverse formation — the stem is not always the shortest form."},
{id:"w10", s:"The ____ of the new runway will double the airport’s capacity.", stem:"LONG", ans:["lengthening"], tags:["wfnoun","wfverb"], diff:4, exp:"long → lengthen → lengthening (the process).", trap:"'length' alone doesn’t fit — the gap needs the action noun."},
{id:"w11", s:"Regular exercise builds both ____ and confidence.", stem:"STRONG", ans:["strength"], tags:["wfnoun","spell"], diff:2, exp:"strong → strength (vowel change).", trap:"Spelling: strenGth — three consonants in a row."},
{id:"w12", s:"The ____ of the tower makes it visible from the whole valley.", stem:"HIGH", ans:["height"], tags:["wfnoun","spell"], diff:2, exp:"high → height.", trap:"Spelling: h-e-i-g-h-t, not 'hight' or 'heighth'."},
{id:"w13", s:"They plan to ____ the main road to four lanes.", stem:"WIDE", ans:["widen"], tags:["wfverb"], diff:2, exp:"wide → widen (verb, -en).", trap:"A verb slot after 'to' — don’t write 'width'."},
{id:"w14", s:"Divers measured the ____ of the lake at its centre.", stem:"DEEP", ans:["depth"], tags:["wfnoun","spell"], diff:2, exp:"deep → depth.", trap:"Spelling: depth, not 'deepth'."},
{id:"w15", s:"To tell the ____ , I never expected to win.", stem:"TRUE", ans:["truth"], tags:["wfnoun"], diff:1, exp:"true → truth; fixed phrase 'to tell the truth'.", trap:"'truly' is the adverb — wrong slot."},
{id:"w16", s:"They had a heated ____ about whose turn it was to pay.", stem:"ARGUE", ans:["argument"], tags:["wfnoun","spell"], diff:2, exp:"argue → argument.", trap:"Spelling: drop the E — arguMent, not 'arguement'."},
{id:"w17", s:"The lift is out of order due to essential ____ work.", stem:"MAINTAIN", ans:["maintenance"], tags:["wfnoun","spell"], diff:3, exp:"maintain → maintenance.", trap:"Spelling: mainTENance — the 'tain' changes to 'ten'."},
{id:"w18", s:"The teacher’s ____ of the rule was admirably clear.", stem:"EXPLAIN", ans:["explanation"], tags:["wfnoun","spell"], diff:2, exp:"explain → explanation.", trap:"Spelling: explAnation — the 'i' disappears."},
{id:"w19", s:"Her ____ of English is almost perfect, apart from a slight accent.", stem:"PRONOUNCE", ans:["pronunciation"], tags:["wfnoun","spell"], diff:3, exp:"pronounce → pronunciation.", trap:"The most famous spelling trap in FCE: pronUnciation, no 'o'."},
{id:"w20", s:"Learning vocabulary requires constant ____ .", stem:"REPEAT", ans:["repetition"], tags:["wfnoun","spell"], diff:3, exp:"repeat → repetition.", trap:"Spelling: repEtition, not 'repeatition'."},
{id:"w21", s:"Pure ____ led her to open the mysterious box.", stem:"CURIOUS", ans:["curiosity"], tags:["wfnoun","spell"], diff:2, exp:"curious → curiosity.", trap:"Drop the U of -ous: curiOsity."},
{id:"w22", s:"He hid his ____ behind a confident smile.", stem:"ANXIOUS", ans:["anxiety"], tags:["wfnoun","spell"], diff:3, exp:"anxious → anxiety.", trap:"anxiety has no 'ous' — the form changes completely."},
{id:"w23", s:"The menu offers a wide ____ of vegetarian dishes.", stem:"VARY", ans:["variety"], tags:["wfnoun"], diff:2, exp:"vary → variety.", trap:"'variation' exists but 'a wide variety of' is the collocation."},
{id:"w24", s:"A daily walk is hugely ____ for your concentration.", stem:"BENEFIT", ans:["beneficial"], tags:["wfadj"], diff:2, exp:"benefit → beneficial.", trap:"'beneficious' doesn’t exist."},
{id:"w25", s:"Buying in bulk is usually more ____ than shopping daily.", stem:"ECONOMY", ans:["economical"], tags:["wfadj"], diff:4, exp:"economical = money-saving. economic = relating to the economy.", trap:"THE classic pair: economic growth / an economical car."},
{id:"w26", s:"The country’s ____ growth slowed sharply last year.", stem:"ECONOMY", ans:["economic"], tags:["wfadj"], diff:4, exp:"economic = of the economy.", trap:"The mirror of w25 — meaning decides the suffix."},
{id:"w27", s:"Who is ____ for booking the rehearsal room this week?", stem:"RESPONSE", ans:["responsible"], tags:["wfadj"], diff:2, exp:"response → responsible.", trap:"-IBLE not -ABLE: responsible."},
{id:"w28", s:"She has an impressive ____ of medieval history.", stem:"KNOW", ans:["knowledge"], tags:["wfnoun","spell"], diff:2, exp:"know → knowledge.", trap:"Spelling: knowLEDGE — d before g."},
{id:"w29", s:"The rapid ____ of the city has put pressure on housing.", stem:"GROW", ans:["growth"], tags:["wfnoun"], diff:1, exp:"grow → growth.", trap:"No E: growth."},
{id:"w30", s:"Our ____ to Buenos Aires was delayed by fog.", stem:"FLY", ans:["flight"], tags:["wfnoun","spell"], diff:1, exp:"fly → flight.", trap:"Irregular formation — not 'flying' in this slot."},
{id:"w31", s:"Going freelance was a brave ____ that paid off.", stem:"CHOOSE", ans:["choice"], tags:["wfnoun","spell"], diff:2, exp:"choose → choice.", trap:"Spelling: choice, not 'choise' or 'chose'."},
{id:"w32", s:"The ____ of the championship final still hurts the fans.", stem:"LOSE", ans:["loss"], tags:["wfnoun","spell"], diff:2, exp:"lose → loss.", trap:"loss (noun) / lose (verb) / loose (adjective) — three different words."},
{id:"w33", s:"The bridge can support a maximum ____ of forty tonnes.", stem:"WEIGH", ans:["weight"], tags:["wfnoun","spell"], diff:1, exp:"weigh → weight.", trap:"Spelling: weiGHt."},
{id:"w34", s:"It is my firm ____ that practice beats talent.", stem:"BELIEVE", ans:["belief"], tags:["wfnoun","spell"], diff:2, exp:"believe → belief.", trap:"The noun loses the final -ve: belief."},
{id:"w35", s:"Old smartphones are rarely ____ after five years of updates.", stem:"RELY", ans:["reliable"], tags:["wfadj","spell"], diff:2, exp:"rely → reliable (y → i).", trap:"reliAble — i before a."},
{id:"w36", s:"Plastic waste causes lasting ____ damage.", stem:"ENVIRONMENT", ans:["environmental"], tags:["wfadj","spell"], diff:1, exp:"environment → environmental.", trap:"Keep the N: environNmental? No — enviroNMENTal, one N before m? Spell it: e-n-v-i-r-o-n-m-e-n-t-a-l."},
{id:"w37", s:"____ , the storm passed before the open-air concert began.", stem:"FORTUNE", ans:["fortunately"], tags:["wfadv"], diff:2, exp:"fortune → fortunately (sentence adverb).", trap:"Polarity check: the news is good, so not 'unfortunately'."},
{id:"w38", s:"____ , the tickets had sold out by the time we arrived.", stem:"LUCK", ans:["unluckily","unfortunately"], tags:["wfadv","wfneg"], diff:3, exp:"Bad news → UNluckily.", trap:"The negative prefix trap in adverb form."},
{id:"w39", s:"These chairs look stylish but are deeply ____ to sit on.", stem:"COMFORT", ans:["uncomfortable"], tags:["wfadj","wfneg"], diff:2, exp:"'but' flips the polarity → UNcomfortable.", trap:"BUT is the signal word for the negative."},
{id:"w40", s:"He drummed his fingers ____ while the page loaded.", stem:"PATIENT", ans:["impatiently"], tags:["wfadv","wfneg"], diff:3, exp:"patient → impatient → impatiently. Double transformation.", trap:"im- before p, AND the -ly: two changes, one word."},
{id:"w41", s:"The actor answered every question with great ____ .", stem:"HONEST", ans:["honesty"], tags:["wfnoun"], diff:2, exp:"honest → honesty.", trap:"'honestity' doesn’t exist."},
{id:"w42", s:"It is ____ to park within ten metres of a junction.", stem:"LEGAL", ans:["illegal"], tags:["wfadj","wfneg"], diff:2, exp:"Rule about NOT doing something → ILlegal (il- before l).", trap:"unlegal/inlegal — the prefix must match the first letter."},
{id:"w43", s:"Finishing the report by Friday is a near ____ .", stem:"POSSIBLE", ans:["impossibility"], tags:["wfnoun","wfneg"], diff:4, exp:"possible → impossible → impossibility: prefix + suffix.", trap:"Double-step words are Cambridge’s favourite hard item."},
{id:"w44", s:"The bus service here is famously ____ .", stem:"REGULAR", ans:["irregular","unreliable"], tags:["wfadj","wfneg"], diff:3, exp:"'famously' + complaint context → IRregular (ir- before r).", trap:"ir- only before r: irregular, irresponsible, irresistible."},
{id:"w45", s:"The smell of fresh bread proved utterly ____ .", stem:"RESIST", ans:["irresistible"], tags:["wfadj","wfneg","spell"], diff:4, exp:"resist → irresistible: ir- prefix AND -ible suffix.", trap:"Double R, then -IBLE: ir-resist-ible."},
{id:"w46", s:"A simple ____ about the dates caused the whole delay.", stem:"UNDERSTAND", ans:["misunderstanding"], tags:["wfnoun","wfneg"], diff:3, exp:"mis- + understanding = wrong understanding.", trap:"MIS- (wrongly), not UN- (not)."},
{id:"w47", s:"The head teacher will not tolerate ____ in class.", stem:"BEHAVE", ans:["misbehaviour","misbehavior"], tags:["wfnoun","wfneg"], diff:3, exp:"behave → misbehaviour.", trap:"'not tolerate' tells you the word is negative."},
{id:"w48", s:"The sudden ____ of the paintings baffled the police.", stem:"APPEAR", ans:["disappearance"], tags:["wfnoun","wfneg"], diff:3, exp:"appear → disappearance ('baffled the police' implies they vanished).", trap:"dis- + appearance; double check -ANCE."},
{id:"w49", s:"Despite the rain, the players showed no ____ to leave the pitch.", stem:"WILLING", ans:["unwillingness","willingness"], tags:["wfnoun","wfneg"], diff:4, exp:"'no willingness to leave' = they wanted to stay; 'no unwillingness' double-negates awkwardly — Cambridge would accept willingness.", trap:"When NO precedes the gap, the noun itself usually stays positive."},
{id:"w50", s:"You need the manager’s ____ before ordering new stock.", stem:"APPROVE", ans:["approval"], tags:["wfnoun"], diff:2, exp:"approve → approval.", trap:"-AL noun: approval, arrival, refusal."},
{id:"w51", s:"Her ____ in the final round earned a standing ovation.", stem:"PERFORM", ans:["performance"], tags:["wfnoun"], diff:1, exp:"perform → performance.", trap:"-ANCE not -ENCE: performance."},
{id:"w52", s:"____ at the workshop is optional but recommended.", stem:"ATTEND", ans:["attendance"], tags:["wfnoun"], diff:2, exp:"attend → attendance.", trap:"-ANCE again — attendance."},
{id:"w53", s:"The two countries finally reached an ____ on fishing rights.", stem:"AGREE", ans:["agreement"], tags:["wfnoun"], diff:1, exp:"agree → agreement.", trap:"If the sentence had been about conflict, DISagreement — always check."},
{id:"w54", s:"Thick fog reduced ____ to less than fifty metres.", stem:"VISIBLE", ans:["visibility"], tags:["wfnoun"], diff:2, exp:"visible → visibility.", trap:"-ITY noun from -IBLE adjective."},
{id:"w55", s:"The hotel apologised for the ____ caused by the building work.", stem:"CONVENIENT", ans:["inconvenience"], tags:["wfnoun","wfneg"], diff:3, exp:"'apologised for' → something bad → INconvenience.", trap:"Negative prefix + noun suffix: in-convenien-ce."},
{id:"w56", s:"Sales figures grew ____ during the holiday season.", stem:"DRAMA", ans:["dramatically"], tags:["wfadv","spell"], diff:3, exp:"drama → dramatic → dramatically.", trap:"-ic → -ically: dramatICALLY, not 'dramaticly'."},
{id:"w57", s:"____ , the museum is closed on the only day I’m free.", stem:"FORTUNE", ans:["unfortunately"], tags:["wfadv","wfneg"], diff:2, exp:"Bad news → UNfortunately.", trap:"Compare w37 — same stem, opposite polarity. Context is everything."},
{id:"w58", s:"The team’s ____ to detail is what wins them contracts.", stem:"ATTEND", ans:["attention"], tags:["wfnoun"], diff:3, exp:"attend → attention (attention to detail).", trap:"Same stem as w52, different noun — collocation decides: attention to detail."},
];

/* ---------- Multiple-Choice Cloze (Part 1 style) ---------- */
FCE.BANK.mcc = [
{id:"m01", s:"I’m afraid I ____ a serious mistake in the booking.", opts:["did","made","took","put"], cor:1, tags:["col","fix"], diff:1, exp:"MAKE a mistake — core collocation.", trap:"DO is the eternal bait with mistake/decision/effort."},
{id:"m02", s:"____ rain forced the organisers to move the ceremony indoors.", opts:["Strong","Hard","Heavy","Powerful"], cor:2, tags:["col"], diff:1, exp:"HEAVY rain (also heavy traffic, heavy smoker).", trap:"STRONG collocates with wind and coffee, not rain."},
{id:"m03", s:"Could you make me a cup of really ____ coffee?", opts:["heavy","strong","powerful","deep"], cor:1, tags:["col"], diff:1, exp:"STRONG coffee.", trap:"The mirror of m02 — swap the partners and both fail."},
{id:"m04", s:"If you don’t wear a scarf, you’ll ____ a cold.", opts:["take","catch","get on","win"], cor:1, tags:["col"], diff:1, exp:"CATCH a cold (illnesses are caught).", trap:"'take a cold' calques from several languages."},
{id:"m05", s:"Hurry up or we’ll ____ the last bus home.", opts:["lose","miss","fail","skip"], cor:1, tags:["col"], diff:1, exp:"MISS the bus/train/flight.", trap:"LOSE the bus is the classic L1 transfer error."},
{id:"m06", s:"Whatever happens, always ____ the truth.", opts:["say","speak","tell","talk"], cor:2, tags:["col","fix"], diff:1, exp:"TELL the truth (also tell a lie, tell a story).", trap:"SAY the truth — wrong partner."},
{id:"m07", s:"Despite months of therapy, the rumour did lasting ____ to her career.", opts:["damage","hurt","wound","break"], cor:0, tags:["col"], diff:3, exp:"DO damage (do harm, do good).", trap:"All four 'mean' injury; only damage partners with DO."},
{id:"m08", s:"The students have ____ remarkable progress this term.", opts:["done","made","taken","given"], cor:1, tags:["col"], diff:1, exp:"MAKE progress.", trap:"DO progress is the bait — progress is created, so MAKE."},
{id:"m09", s:"The award ceremony will ____ place in the town hall.", opts:["take","have","get","hold"], cor:0, tags:["fix"], diff:1, exp:"TAKE place = happen.", trap:"HOLD an event is fine, but the fixed phrase is take place."},
{id:"m10", s:"After hours of negotiation, the two sides finally ____ an agreement.", opts:["arrived","reached","got","came"], cor:1, tags:["col"], diff:2, exp:"REACH an agreement (also reach a decision/conclusion).", trap:"ARRIVE AT an agreement needs AT; bare 'arrived' fails."},
{id:"m11", s:"She ____ the world record by almost half a second.", opts:["beat","won","broke","defeated"], cor:2, tags:["col"], diff:2, exp:"BREAK a record.", trap:"You BEAT people, WIN prizes, BREAK records."},
{id:"m12", s:"Whatever you promised, you must ____ your word.", opts:["hold","keep","stay","save"], cor:1, tags:["col","fix"], diff:2, exp:"KEEP your word/promise.", trap:"HOLD your word — almost right, completely wrong."},
{id:"m13", s:"He ____ his temper when the referee ignored the foul.", opts:["lost","missed","dropped","broke"], cor:0, tags:["col","fix"], diff:2, exp:"LOSE your temper = get angry.", trap:"BREAK your temper doesn’t exist."},
{id:"m14", s:"The school fair ____ over two thousand euros for charity.", opts:["raised","rose","lifted","earned"], cor:0, tags:["col"], diff:2, exp:"RAISE money (for charity).", trap:"RISE is intransitive — it can’t take an object."},
{id:"m15", s:"It’s getting harder to ____ a living as a freelance photographer.", opts:["win","gain","earn","make do"], cor:2, tags:["col","fix"], diff:2, exp:"EARN a living (also make a living).", trap:"WIN a living — money is earned, not won."},
{id:"m16", s:"I didn’t ____ the joke until everyone had stopped laughing.", opts:["catch","get","take","realise"], cor:1, tags:["col","pv"], diff:2, exp:"GET a joke = understand it.", trap:"REALISE needs a clause, and you don’t 'catch' jokes in standard usage."},
{id:"m17", s:"The committee ____ to a unanimous conclusion after midnight.", opts:["came","reached","arrived","drew"], cor:0, tags:["col","prep"], diff:3, exp:"COME TO a conclusion (the TO is already in the sentence).", trap:"REACH a conclusion is right WITHOUT 'to' — the preposition decides."},
{id:"m18", s:"My grandparents ____ me up while my parents worked abroad.", opts:["grew","brought","raised up","carried"], cor:1, tags:["pv"], diff:2, exp:"BRING somebody UP = raise a child.", trap:"GROW UP is what the child does; RAISE never takes 'up'."},
{id:"m19", s:"This song always ____ me of our summer in Galicia.", opts:["remembers","reminds","recalls","memorises"], cor:1, tags:["col"], diff:2, exp:"REMIND somebody OF something.", trap:"REMEMBER can’t take a person + of: things remind YOU."},
{id:"m20", s:"The new tax will mainly ____ small online businesses.", opts:["effect","affect","afflict","infect"], cor:1, tags:["col","spell"], diff:3, exp:"AFFECT (verb) = have an effect on.", trap:"EFFECT is the noun; the verb slot wants affect."},
{id:"m21", s:"The team’s confidence ____ after the third straight defeat.", opts:["sank","drowned","dipped under","descended"], cor:0, tags:["col"], diff:4, exp:"Confidence/spirits SANK.", trap:"All options are 'go down' words; only sink collocates with confidence."},
{id:"m22", s:"We had great ____ finding a parking space near the stadium.", opts:["problem","difficulty","obstacle","effort"], cor:1, tags:["col","ger"], diff:3, exp:"have difficulty + -ing.", trap:"'great problem' would need 'a'; difficulty is uncountable here."},
{id:"m23", s:"The travel agency ____ us a full refund for the cancelled tour.", opts:["proposed","suggested","offered","invited"], cor:2, tags:["ger","col"], diff:2, exp:"OFFER somebody something.", trap:"SUGGEST never takes person + object: 'suggested us' is impossible."},
{id:"m24", s:"The doctor ____ him to cut down on sugary drinks.", opts:["said","suggested","advised","insisted"], cor:2, tags:["rep","ger"], diff:2, exp:"ADVISE somebody TO do.", trap:"SAY and INSIST can’t take object + to-infinitive."},
{id:"m25", s:"They ____ us from entering the site without helmets.", opts:["avoided","prevented","refused","forbade to"], cor:1, tags:["prep","rep"], diff:3, exp:"PREVENT somebody FROM + -ing.", trap:"AVOID takes -ing but no object+from; the FROM in the sentence decides."},
{id:"m26", s:"He flatly ____ to apologise for the comment.", opts:["denied","refused","rejected","resisted"], cor:1, tags:["ger","rep"], diff:3, exp:"REFUSE TO do.", trap:"DENY + -ing (deny doing); refuse + to — the TO in the sentence is the clue."},
{id:"m27", s:"She ____ ever having seen the document before.", opts:["refused","denied","rejected","disagreed"], cor:1, tags:["ger","rep"], diff:3, exp:"DENY + -ing (having seen).", trap:"The mirror of m26 — the -ING after the gap is the clue."},
{id:"m28", s:"I’ll lend you my notes ____ you photocopy them today.", opts:["unless","in case","provided","whether"], cor:2, tags:["cond","link"], diff:3, exp:"PROVIDED (that) = on condition that.", trap:"UNLESS would reverse the logic; IN CASE is preparation, not condition."},
{id:"m29", s:"Take some cash ____ the card machine isn’t working.", opts:["unless","in case","so that","provided"], cor:1, tags:["cond","link"], diff:3, exp:"IN CASE = as a precaution.", trap:"SO THAT expresses purpose, not precaution."},
{id:"m30", s:"____ the high price, the concert sold out in minutes.", opts:["Although","Despite","Even though","However"], cor:1, tags:["link"], diff:2, exp:"DESPITE + noun phrase.", trap:"Although/even though need a clause with a verb."},
{id:"m31", s:"I had ____ finished dinner when the doorbell rang.", opts:["yet","hardly","almost not","nearly not"], cor:1, tags:["fix","inv"], diff:3, exp:"HARDLY = only just.", trap:"'almost not finished' is not natural English."},
{id:"m32", s:"____ to the forecast, the heatwave will break on Friday.", opts:["According","Regarding","Referring","Depending"], cor:0, tags:["depprep","link"], diff:2, exp:"ACCORDING to = as stated by.", trap:"All four take TO, but only ACCORDING reports a source."},
{id:"m33", s:"We left at dawn ____ to avoid the holiday traffic.", opts:["for","so as","in order that","because"], cor:1, tags:["link","ger"], diff:3, exp:"SO AS to + infinitive = purpose.", trap:"IN ORDER THAT needs a clause; the TO after the gap decides."},
{id:"m34", s:"The instructions were ____ confusing that nobody finished the task.", opts:["such","so","too","very"], cor:1, tags:["comp","det"], diff:2, exp:"SO + adjective + that.", trap:"SUCH needs a noun; TOO doesn’t combine with that-clauses."},
{id:"m35", s:"It was ____ a tense match that I could barely watch.", opts:["so","such","too","quite"], cor:1, tags:["comp","det"], diff:2, exp:"SUCH + a + adjective + noun + that.", trap:"The mirror of m34 — the noun 'match' demands SUCH."},
{id:"m36", s:"You can ____ my number from reception if you lose it.", opts:["lend","borrow","get","rent"], cor:2, tags:["col"], diff:2, exp:"GET information from somewhere.", trap:"BORROW/LEND apply to things you return — not phone numbers."},
{id:"m37", s:"Could you ____ me your charger until lunchtime?", opts:["borrow","lend","rent","loan to"], cor:1, tags:["col"], diff:1, exp:"LEND = give temporarily (lender’s side).", trap:"BORROW is the receiver’s verb: I borrow FROM you, you lend TO me."},
{id:"m38", s:"The museum was ____ interesting than the guidebook suggested.", opts:["very","far more","much","most"], cor:1, tags:["comp"], diff:2, exp:"FAR MORE + adjective + than.", trap:"'much interesting' lacks MORE; 'very' can’t modify a comparative."},
{id:"m39", s:"The view from the lighthouse simply ____ our breath away.", opts:["took","caught","stole","blew"], cor:0, tags:["fix"], diff:2, exp:"TAKE your breath away = amaze.", trap:"BLEW is tempting via 'blew us away' — but breath pairs with TAKE."},
{id:"m40", s:"I’m not in the ____ for a party tonight, honestly.", opts:["feeling","spirit","mood","sense"], cor:2, tags:["fix"], diff:2, exp:"be in the MOOD for = feel like.", trap:"SPIRIT(S) is about morale, not desire."},
{id:"m41", s:"The startup went ____ after barely a year of trading.", opts:["broke","bankrupt","poor","penniless"], cor:1, tags:["col"], diff:3, exp:"GO BANKRUPT (companies).", trap:"GO BROKE is informal/personal; companies go bankrupt."},
{id:"m42", s:"Volunteers ____ a vital part in the festival’s success.", opts:["make","play","do","hold"], cor:1, tags:["col","fix"], diff:2, exp:"PLAY a part/role in.", trap:"MAKE a part — wrong partner; roles are played."},
{id:"m43", s:"The trial ____ several weaknesses in the security system.", opts:["showed up","revealed","appeared","emerged"], cor:1, tags:["col"], diff:3, exp:"REVEAL weaknesses (transitive).", trap:"EMERGE/APPEAR are intransitive — they can’t take an object."},
{id:"m44", s:"I can’t ____ the difference between the twins.", opts:["say","tell","notice on","make"], cor:1, tags:["fix","col"], diff:2, exp:"TELL the difference = distinguish.", trap:"SAY the difference — same trap family as say/tell the truth."},
{id:"m45", s:"The festival was called off ____ to the approaching storm.", opts:["due","owing for","because","thanks"], cor:0, tags:["link","depprep"], diff:2, exp:"DUE TO = because of.", trap:"BECAUSE needs OF before a noun; THANKS TO is for positive causes."},
{id:"m46", s:"She takes ____ her role as captain very seriously.", opts:["over","on","up","after"], cor:1, tags:["pv"], diff:3, exp:"TAKE ON a role/responsibility.", trap:"Take over = seize control; take up = start a hobby; take after = resemble."},
{id:"m47", s:"It took her months to get ____ the disappointment of the rejection.", opts:["over","through","across","by"], cor:0, tags:["pv"], diff:2, exp:"GET OVER = recover from.", trap:"GET THROUGH = survive/finish — close, but the idiom for recovery is get over."},
{id:"m48", s:"How do you ____ up with such a noisy flatmate?", opts:["take","put","get","stand"], cor:1, tags:["pv"], diff:2, exp:"PUT up with = tolerate.", trap:"STAND alone means tolerate, but with 'up with' only PUT works."},
{id:"m49", s:"The deal fell ____ at the last minute over payment terms.", opts:["off","down","through","apart"], cor:2, tags:["pv"], diff:4, exp:"FALL THROUGH = (of plans) fail to happen.", trap:"Fall apart = disintegrate; fall down = collapse physically."},
{id:"m50", s:"I came ____ a fascinating podcast about memory athletes.", opts:["across","up","over","into"], cor:0, tags:["pv"], diff:2, exp:"COME ACROSS = find by chance.", trap:"Come up with = invent — needs 'with'."},
{id:"m51", s:"Be sensible — don’t let one bad mark ____ you off studying.", opts:["take","put","set","turn"], cor:1, tags:["pv"], diff:3, exp:"PUT somebody OFF something = discourage.", trap:"Turn off = switch off / repel romantically; the study idiom is put off."},
{id:"m52", s:"Her acting career really took ____ after that TV series.", opts:["off","up","over","on"], cor:0, tags:["pv"], diff:2, exp:"TAKE OFF = suddenly succeed.", trap:"Careers take OFF like planes — up/over/on all fail."},
{id:"m53", s:"We’ve ____ out of printer paper again.", opts:["gone","used","run","finished"], cor:2, tags:["pv"], diff:1, exp:"RUN out of = exhaust the supply.", trap:"USED UP would need no 'out of'."},
{id:"m54", s:"The alarm went ____ at 3 a.m. for no reason.", opts:["off","on","out","up"], cor:0, tags:["pv"], diff:2, exp:"GO OFF = ring/explode.", trap:"Counter-intuitive: alarms go OFF when they start making noise."},
{id:"m55", s:"Slow down — I can’t keep ____ with you in these shoes.", opts:["on","up","over","along"], cor:1, tags:["pv"], diff:2, exp:"KEEP UP WITH = match the pace of.", trap:"Keep on = continue; the WITH in the sentence points to up."},
{id:"m56", s:"He’s very easy to get ____ with — everyone likes him.", opts:["over","along","through","away"], cor:1, tags:["pv"], diff:2, exp:"GET ALONG/ON WITH = have a good relationship.", trap:"Get away with = escape punishment — a very different compliment."},
];

/* ---------- Full passages for mock tests ---------- */
FCE.BANK.passages = {
p1:[{ id:"pp1a", title:"The science of first impressions",
  text:"Psychologists have long been fascinated by how quickly we (1) judgements about people we have never met. Research suggests that it (2) us less than a second to decide whether a stranger seems trustworthy. These snap decisions are not always accurate, but they are remarkably hard to (3) once they have formed. In one well-known experiment, students watched silent video clips of lecturers and rated their confidence. Their ratings (4) closely with the scores given by students who had attended the lecturers’ classes for an entire term. The findings (5) that we should perhaps place less weight on lengthy interviews. Some companies have already (6) account of this research and now use structured tasks instead of informal chats. Critics, however, point out that quick judgements can (7) to unfair treatment of candidates who are simply shy. The honest conclusion is that first impressions are powerful, occasionally useful and frequently (8) .",
  gaps:[
   {n:1, opts:["do","form","take","put"], cor:1, exp:"FORM a judgement/opinion.", tags:["col"]},
   {n:2, opts:["takes","lasts","spends","needs"], cor:0, exp:"It TAKES + person + time.", tags:["fix"]},
   {n:3, opts:["shake","shift","budge","undo"], cor:0, exp:"hard to SHAKE (off) an impression.", tags:["col"]},
   {n:4, opts:["agreed","matched","compared","corresponded"], cor:3, exp:"CORRESPOND with = match closely.", tags:["col","prep"]},
   {n:5, opts:["propose","suggest","advise","insist"], cor:1, exp:"Findings SUGGEST that…", tags:["col","rep"]},
   {n:6, opts:["made","got","taken","given"], cor:2, exp:"TAKE account of = consider.", tags:["fix"]},
   {n:7, opts:["lead","cause","result","bring"], cor:0, exp:"LEAD to (cause needs no 'to'; result needs 'in').", tags:["prep","col"]},
   {n:8, opts:["mistaken","wrong","false","incorrect"], cor:0, exp:"Impressions are MISTAKEN — natural collocate for judgements.", tags:["col"]},
  ]},
 { id:"pp1b", title:"Why we love lists",
  text:"From shopping lists to top-ten film rankings, human beings seem to take deep (1) in putting things in order. Psychologists believe lists appeal to us because they (2) the chaos of daily life feel manageable. Crossing items off, meanwhile, (3) us a small reward: each tick of the pen (4) a tiny sense of achievement directly to the brain. There is, (5) , a downside. Writing tasks down can trick the mind into feeling that the work has already been (6) with, which may explain why so many to-do lists are abandoned by lunchtime. To avoid this trap, experts suggest keeping lists short, (7) than trying to capture everything, and limiting each day to a few important items that you will actually carry (8) .",
  gaps:[
   {n:1, opts:["pleasure","enjoyment","fun","interest"], cor:0, exp:"TAKE PLEASURE IN — fixed collocation ('take AN interest in' would need the article).", tags:["fix","col"]},
   {n:2, opts:["make","let","cause","leave"], cor:0, exp:"MAKE + object + feel.", tags:["col","ger"]},
   {n:3, opts:["gives","does","makes","puts"], cor:0, exp:"GIVE somebody a reward.", tags:["col"]},
   {n:4, opts:["delivers","results","arrives","reaches"], cor:0, exp:"DELIVER a sense of achievement (transitive); result/arrive are intransitive.", tags:["col"]},
   {n:5, opts:["however","although","despite","whereas"], cor:0, exp:"HOWEVER between commas; the others need clauses/nouns.", tags:["link"]},
   {n:6, opts:["dealt","done","sorted","handled"], cor:0, exp:"DEALT WITH — only 'deal' partners WITH here.", tags:["pv","prep"]},
   {n:7, opts:["rather","more","better","sooner"], cor:0, exp:"RATHER THAN + -ing = instead of.", tags:["link","comp"]},
   {n:8, opts:["out","on","over","off"], cor:0, exp:"CARRY OUT = actually do/complete.", tags:["pv"]},
  ]}],
p2:[{ id:"pp2a", title:"A city without cars",
  text:"Pontevedra, a small city in the north-west of Spain, has become famous (1) banning cars from its historic centre. The transformation began more than twenty years (2) , when the newly elected mayor decided that the city belonged to people rather (3) to traffic. At first, shop owners feared they would lose customers. (4) the contrary, business improved as pedestrians lingered in streets (5) children could finally play safely. Air pollution has fallen dramatically, and hardly (6) serious traffic accidents have been recorded since the scheme began. Other cities have taken note: delegations arrive every month to find (7) how the model works. The mayor’s advice to them is simple: do not ask drivers for permission — give people a better city, and they will soon get used (8) walking.",
  gaps:[
   {n:1, ans:["for"], gt:"prep", exp:"famous FOR + -ing.", tags:["prep"]},
   {n:2, ans:["ago"], gt:"adv", exp:"twenty years AGO + past simple.", tags:["aux"]},
   {n:3, ans:["than"], gt:"link", exp:"rather THAN.", tags:["link","comp"]},
   {n:4, ans:["on"], gt:"fixphrase", exp:"ON the contrary.", tags:["depprep"]},
   {n:5, ans:["where"], gt:"rel", exp:"streets WHERE children could play.", tags:["rel"]},
   {n:6, ans:["any"], gt:"det", exp:"hardly ANY accidents.", tags:["det"]},
   {n:7, ans:["out"], gt:"adv", exp:"find OUT = discover.", tags:["pv"]},
   {n:8, ans:["to"], gt:"prep", exp:"get used TO + -ing.", tags:["ger"]},
  ]},
 { id:"pp2b", title:"The violin maker",
  text:"In a quiet workshop in Cremona, Sofia Ruiz is one of the few craftspeople (1) still make violins entirely by hand. It can take (2) to three months to finish a single instrument, and no two are ever exactly the (3) . Sofia was introduced to the craft by her grandfather, (4) workshop she inherited when she was only twenty-five. Although machines could speed up the process, she insists (5) using traditional methods. “If I hurried, the wood would not be ready,” she explains. “You cannot make (6) instrument sing unless the timber has rested.” Her violins are now played (7) some of the finest musicians in Europe, several of whom wait years for one. As Sofia puts it, “Good things take time — and great things take a little (8) .”",
  gaps:[
   {n:1, ans:["who","that"], gt:"rel", exp:"people WHO/THAT still make.", tags:["rel"]},
   {n:2, ans:["up"], gt:"adv", exp:"take UP to three months.", tags:["fix"]},
   {n:3, ans:["same"], gt:"fixphrase", exp:"the SAME.", tags:["art","fix"]},
   {n:4, ans:["whose"], gt:"rel", exp:"WHOSE workshop = possession.", tags:["rel"]},
   {n:5, ans:["on","upon"], gt:"prep", exp:"insist ON + -ing.", tags:["prep","ger"]},
   {n:6, ans:["an"], gt:"art", exp:"make AN instrument sing.", tags:["art"]},
   {n:7, ans:["by"], gt:"prep", exp:"passive agent: played BY musicians.", tags:["pass","prep"]},
   {n:8, ans:["longer","more"], gt:"comp", exp:"a little LONGER/MORE.", tags:["comp"]},
  ]},
 { id:"pp2c", title:"The lost art of handwriting",
  text:"Not so long ago, every letter, list and birthday card was written (1) hand. Today, many of us can go for weeks (2) picking up a pen at all. Researchers, however, argue that handwriting, (3) may look old-fashioned, still matters. Forming letters slowly seems to help children learn to read, and students (4) take notes on paper often remember lectures better than those who type. (5) is more, a handwritten note carries an emotional weight that no message on a screen can match. Schools in several countries have therefore decided to give handwriting lessons another (6) , insisting that pupils practise every day. It may take time, but experts believe the skill is well (7) saving — even if our fingers have got used (8) keyboards.",
  gaps:[
   {n:1, ans:["by"], gt:"prep", exp:"written BY hand — fixed phrase.", tags:["depprep"]},
   {n:2, ans:["without"], gt:"prep", exp:"WITHOUT + -ing (picking).", tags:["prep","ger"]},
   {n:3, ans:["which"], gt:"rel", exp:"Non-defining clause about a thing → WHICH (never THAT after a comma).", tags:["rel"]},
   {n:4, ans:["who","that"], gt:"rel", exp:"students WHO/THAT take notes.", tags:["rel"]},
   {n:5, ans:["what"], gt:"fixphrase", exp:"WHAT is more = furthermore.", tags:["fix","rel"]},
   {n:6, ans:["go","try","chance"], gt:"fixphrase", exp:"give something another GO/TRY/CHANCE.", tags:["fix","col"]},
   {n:7, ans:["worth"], gt:"fixphrase", exp:"well WORTH + -ing.", tags:["fix","ger"]},
   {n:8, ans:["to"], gt:"prep", exp:"get used TO something.", tags:["ger","prep"]},
  ]},
 { id:"pp2d", title:"Why queues feel longer",
  text:"Have you ever felt that the queue you choose always turns (1) to be the slowest one? According to psychologists, it is not bad luck (2) simple mathematics: with several lines open, the chance that yours is the fastest is low. Our sense of time makes things (3) worse. Minutes spent doing nothing feel far longer (4) minutes spent occupied, which is (5) many airports now make passengers walk further to collect their bags — the walking fills the wait. Companies also know that we hate watching others move (6) us, so single queues serving several counters have become common. (7) you find yourself stuck in line again, remember: it probably is not slower; it just feels (8) it.",
  gaps:[
   {n:1, ans:["out"], gt:"adv", exp:"TURN OUT to be = prove to be.", tags:["pv"]},
   {n:2, ans:["but"], gt:"link", exp:"not X BUT Y — contrastive pair.", tags:["link"]},
   {n:3, ans:["even"], gt:"adv", exp:"EVEN worse — strengthens a comparative.", tags:["comp","det"]},
   {n:4, ans:["than"], gt:"comp", exp:"longer THAN.", tags:["comp"]},
   {n:5, ans:["why"], gt:"rel", exp:"which is WHY = and for that reason.", tags:["rel","link"]},
   {n:6, ans:["past","ahead"], gt:"prep", exp:"move PAST us (or AHEAD of us — but one word only, so past).", tags:["prep"]},
   {n:7, ans:["if","when","whenever","should"], gt:"link", exp:"IF/WHEN(EVER) you find yourself…; formal SHOULD also fits.", tags:["cond","link"]},
   {n:8, ans:["like"], gt:"fixphrase", exp:"it feels LIKE it.", tags:["fix","prep"]},
  ]},
 { id:"pp2e", title:"A library of things",
  text:"How often do you actually use the drill you bought years ago? Most power tools are used for (1) than fifteen minutes in their whole lives. That is the thinking (2) the “library of things”, a scheme that lets people borrow objects instead (3) buying them. Members pay a small annual fee, after (4) they can take home anything from tents to sewing machines. Supporters say the idea saves money and cuts waste at the (5) time. Critics wondered at first whether anyone (6) bother to return a borrowed ladder, but in practice items rarely go missing. The first British branch opened more than a decade (7) , and similar libraries have (8) been set up across Europe.",
  gaps:[
   {n:1, ans:["less","fewer"], gt:"comp", exp:"for LESS than fifteen minutes (duration → less).", tags:["comp","det"]},
   {n:2, ans:["behind"], gt:"prep", exp:"the thinking BEHIND an idea.", tags:["prep","col"]},
   {n:3, ans:["of"], gt:"prep", exp:"instead OF + -ing.", tags:["prep","ger"]},
   {n:4, ans:["which"], gt:"rel", exp:"after WHICH — preposition + which.", tags:["rel"]},
   {n:5, ans:["same"], gt:"fixphrase", exp:"at the SAME time.", tags:["fix","art"]},
   {n:6, ans:["would"], gt:"modal", exp:"wondered whether anyone WOULD bother — future-in-the-past.", tags:["modal","rep"]},
   {n:7, ans:["ago"], gt:"adv", exp:"a decade AGO + past simple.", tags:["aux"]},
   {n:8, ans:["since","also","now","already"], gt:"adv", exp:"have SINCE been set up (= since then); also/now/already also fit grammatically.", tags:["aux","pass"]},
  ]},
 { id:"pp2f", title:"Swimming in winter",
  text:"Every morning at dawn, whatever the weather, a group of swimmers gathers (1) the edge of a lake in the hills. None (2) them wears a wetsuit, even in January, when they sometimes have to break the ice before getting (3) . Cold-water swimming has grown enormously in popularity, and not (4) reason: regular swimmers report better sleep, brighter moods and fewer winter illnesses. Doctors advise beginners to take (5) slowly, starting in summer and staying in the water for (6) more than a few minutes at first. The cold, they warn, must never be underestimated, no (7) how experienced you are. Still, ask any member of the dawn club and they will tell you it is by (8) the best part of their day.",
  gaps:[
   {n:1, ans:["at","by","on"], gt:"prep", exp:"gathers AT/BY the edge.", tags:["prep"]},
   {n:2, ans:["of"], gt:"prep", exp:"NONE OF them + singular verb.", tags:["det","prep"]},
   {n:3, ans:["in"], gt:"adv", exp:"getting IN (into the water).", tags:["pv"]},
   {n:4, ans:["without"], gt:"prep", exp:"not WITHOUT reason = with good reason.", tags:["fix","prep"]},
   {n:5, ans:["it","things"], gt:"pron", exp:"take IT slowly — dummy it.", tags:["pron","fix"]},
   {n:6, ans:["no"], gt:"det", exp:"for NO more than = only.", tags:["det","comp"]},
   {n:7, ans:["matter"], gt:"fixphrase", exp:"no MATTER how = however.", tags:["fix"]},
   {n:8, ans:["far"], gt:"fixphrase", exp:"by FAR the best — superlative intensifier.", tags:["fix","comp"]},
  ]}],
p3:[{ id:"pp3a", title:"Why we forget names",
  text:"Forgetting someone’s name seconds after being introduced is an almost universal (1)EMBARRASS. Scientists offer a simple (2)EXPLAIN: a name is an arbitrary label with no (3)MEANING connection to a person’s face. Unlike a job or a hobby, it gives our memory nothing to hold on to. (4)FORTUNE, there are proven ways to fight this. Memory athletes turn names into vivid images, the more (5)RIDICULE the better, and attach them to a distinctive facial feature. This technique feels (6)NATURE at first, but with practice it becomes automatic. Researchers also stress the (7)IMPORTANT of simply repeating the name aloud during the conversation. Used together, these strategies can produce a remarkable (8)IMPROVE in social memory within weeks.",
  gaps:[
   {n:1, stem:"EMBARRASS", ans:["embarrassment"], exp:"Noun needed: embarrassment.", tags:["wfnoun","spell"]},
   {n:2, stem:"EXPLAIN", ans:["explanation"], exp:"explain → explanation.", tags:["wfnoun","spell"]},
   {n:3, stem:"MEANING", ans:["meaningful"], exp:"meaningful connection.", tags:["wfadj"]},
   {n:4, stem:"FORTUNE", ans:["fortunately"], exp:"Good news → fortunately.", tags:["wfadv"]},
   {n:5, stem:"RIDICULE", ans:["ridiculous"], exp:"ridicule → ridiculous.", tags:["wfadj"]},
   {n:6, stem:"NATURE", ans:["unnatural"], exp:"'at first, but…' → UNnatural.", tags:["wfadj","wfneg"]},
   {n:7, stem:"IMPORTANT", ans:["importance"], exp:"the importance of.", tags:["wfnoun"]},
   {n:8, stem:"IMPROVE", ans:["improvement"], exp:"improve → improvement.", tags:["wfnoun"]},
  ]},
 { id:"pp3b", title:"The rise of urban beekeeping",
  text:"Beekeeping, once a strictly rural (1)OCCUPY, is enjoying an unexpected boom on city rooftops. Urban hives can be surprisingly (2)PRODUCT, since parks and gardens offer flowers from early spring until late autumn. Supporters argue that city honey is purer than its country cousin because urban plants receive fewer chemical (3)TREAT. Beginners, however, often underestimate the (4)RESPONSIBLE involved in keeping thousands of stinging insects on a roof. Courses teach the (5)BASIC of hive management, and most cities now require formal (6)REGISTER of every colony. Done properly, beekeeping brings real (7)ENVIRONMENT benefits, boosting the (8)POLLINATE of trees and flowers across entire neighbourhoods.",
  gaps:[
   {n:1, stem:"OCCUPY", ans:["occupation"], exp:"occupy → occupation.", tags:["wfnoun"]},
   {n:2, stem:"PRODUCT", ans:["productive"], exp:"productive hives.", tags:["wfadj"]},
   {n:3, stem:"TREAT", ans:["treatments"], exp:"Plural needed: fewer treatmentS.", tags:["wfnoun"]},
   {n:4, stem:"RESPONSIBLE", ans:["responsibility"], exp:"responsibility (noun).", tags:["wfnoun"]},
   {n:5, stem:"BASIC", ans:["basics"], exp:"the basicS of — plural.", tags:["wfnoun"]},
   {n:6, stem:"REGISTER", ans:["registration"], exp:"register → registration.", tags:["wfnoun"]},
   {n:7, stem:"ENVIRONMENT", ans:["environmental"], exp:"environmental benefits.", tags:["wfadj"]},
   {n:8, stem:"POLLINATE", ans:["pollination"], exp:"pollinate → pollination.", tags:["wfnoun"]},
  ]}],
};
